import {
  Baby,
  Briefcase,
  CalendarSync,
  Car,
  CreditCard,
  Dumbbell,
  Film,
  Gift,
  HandCoins,
  Heart,
  Home,
  Lightbulb,
  PawPrint,
  PiggyBank,
  Pizza,
  Plane,
  Shirt,
  ShoppingCart,
  Smartphone,
  TrendingUp,
  Wrench,
} from "lucide-react"

export const iconOptions = [
  { value: "housing", label: "Habitação", icon: Home },
  { value: "groceries", label: "Compras", icon: ShoppingCart },
  { value: "transport", label: "Transporte", icon: Car },
  { value: "health", label: "Saúde", icon: Heart },
  { value: "entertainment", label: "Lazer", icon: Film },
  { value: "dining", label: "Alimentação", icon: Pizza },
  { value: "travel", label: "Viagem", icon: Plane },
  { value: "gifts", label: "Presentes", icon: Gift },
  { value: "savings", label: "Poupança", icon: PiggyBank },
  { value: "investments", label: "Investimentos", icon: TrendingUp },
  { value: "creditCard", label: "Cartão", icon: CreditCard },
  { value: "taxes", label: "Impostos", icon: HandCoins },
  { value: "work", label: "Trabalho", icon: Briefcase },
  { value: "maintenance", label: "Manutenção", icon: Wrench },
  { value: "kids", label: "Filhos", icon: Baby },
  { value: "pets", label: "Pets", icon: PawPrint },
  { value: "tech", label: "Tecnologia", icon: Smartphone },
  { value: "sports", label: "Esporte", icon: Dumbbell },
  { value: "signature", label: "Assinatura", icon: CalendarSync },
  { value: "clothing", label: "Roupas", icon: Shirt },
  { value: "ideas", label: "Extra", icon: Lightbulb },
] as const

export type IconOption = (typeof iconOptions)[number]
